In [1]:
# functions creating new arrays

In [3]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.identity(4)   #Create a square N x N identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.eye(4)   #Create a square N x N identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# changing the data type use array.astype(type)
# Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.

In [13]:
# axis 0 is row and axis 1 is column
#[:,:]

In [15]:
# transpose 
#arr.T
# dot product
#np.dot(arr.T,arr)

# trnaspose in multidimensional array
# swapaxes


#### save and  load array

In [16]:
# save 
arr= np.arange(10)

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.save("save_array",arr)

In [19]:
# load array
np.load("save_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# save multiple in zip archive using np.savez
#np.savez("array1_archive.npz",a=arr,b=arr)
# load
# arch=np.load('array1_archive.npz')    ## When loading an .npz file, you get back a dict-like object which loads the individual  arrays lazily:
# arch['b']